### ISSUE TITLE
How can I use the command org-cliplink-capture?

### ISSUE THREAD

**Issue by mrbig033** [rexim/org-cliplink#104]
I have no idea how to use it, but from the description it could be very useful!

**Comment by alphapapa** [comment]
I don't mean to "poach' users, because org-cliplink is a great package, but I'm guessing it's used something like this `org-capture-templates` template would be used with `org-web-tools`:
```el
("wc" "org-cliplink" entry
      (file "")
      "* %(org-web-tools--org-link-for-url) :website:

%U %?")
```
