### ISSUE TITLE
Support multiple url

### ISSUE THREAD

**Issue by azzamsa** [rexim/org-cliplink#114]
Hi

I think this is outside org-'clip'link roadmap. But do you consider to support multiple url / batch fetching.

e.g

1) I have 3 or more url

```
https://foo
https://bar
https://baz
```

2) select region then do `org-cliplink`. Or select region -> copy to clipboard -> org-cliplink then detect how many url in clipboard then parse it one by one.

the result will be

```
Foo title
Bar title
Baz title
```

Thanks :)

**Comment by rexim** [comment]
@azzamsa sounds like an interesting idea. I'll see what we can do about it. Thanks!

**Comment by baerrach** [comment]
Have you considered using https://github.com/magnars/multiple-cursors.el?

Highlight the block, enable multiple cursors, run the org-cliplink command.

That should do it.

**Comment by azzamsa** [comment]
![Peek 2020-08-26 08-06 - org-cliplink](https://user-images.githubusercontent.com/17734314/91243008-10f57b00-e773-11ea-8a0a-f5f295ffaaa9.gif)

@baerrach is that works in your side?

---

@rexim I don't think I need this feature anymore. Now I organize my workflow to be more simple. Adding this feature require many changes in the codebase (IMHO), and the result is that instead of doing what org-cliplink created for, it goes out of scope.

**Comment by baerrach** [comment]
@azzamsa 
I dont have this tool installed, but bumped into it on the interwebs.

Multiple cursors doesn't work with `M-X` extended commands, you need to use key bindings...

**Comment by azzamsa** [comment]
> Highlight the block, enable multiple cursors, run the org-cliplink comman

I don't think it works, since org-cliplink need a link to be placed in the clipboard.

**Comment by azzamsa** [comment]
I don't need this feature anymore. I changed my workflow. I don't do copy-paste much URL as before.
Implementing this feature could lead to massive change on org-cliplink codebase with less benefit.
