### ISSUE TITLE
Check if link title fetched correctly

### ISSUE THREAD

**Issue by azzamsa** [rexim/org-cliplink#115]
Hi rexim.

This is not a bug. I open this issue so that you can rethink the
program design or just let the old way.

Can we do some action if org-link didn't success to fetch link's title.
The option is to show the error via minibuffer, or to re-fetch the title until n times.

E.g org-link will act "smarter" upon "400"

```
[[https://wiki.debian.org/NewInBuster][400 Bad Request]]
```

Thanks :)

**Comment by rexim** [comment]
@azzamsa What if the server returned 200 OK with the page title actually being "400 Bad Request"?

**Comment by azzamsa** [comment]
Oh yes. I don't consider that case. 

So in my case, is the debian server already return 200 OK or it just return 400 ?

>  What if the server returned 200 OK with the page title actually being "400 Bad Request"?

But considering this scenario exist, I think it's better to stay with the former flow.
The solution for user is just to re-call org-link again.
