### ISSUE TITLE
Link clipping is failing more often

### ISSUE THREAD

**Issue by notuntoward** [rexim/org-cliplink#116]
I like org-cliplink a lot, but lately, it fails to work on an increasing number of websites.  For example, if this is in my buffer:

https://www.nrdc.org/experts/jackie-wong/doe-stalls-clean-energy-rd-risking-jobs-competitiveness

And if I type `M-x org-cliplink`, I get the following emacs messages

Contacting host: www.nrdc.org:443
url-http: Could not create connection to www.nrdc.org:443

and no clipping is done.

Still, org-cliplink works on many sites, just fewer and fewer of them.

This is on GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30 and the latest org-mode

**Comment by rexim** [comment]
This link works perfectly for me in Emacs 25.3.1

**Comment by azzamsa** [comment]
Confirm. This link works for me. Emacs 26.1

```
[[https://www.nrdc.org/experts/jackie-wong/doe-stalls-clean-energy-rd-risking-jobs-competitiveness][DOE Stalls Clean Energy R&D: Risking Jobs & Competitivene...]]
```

**Comment by notuntoward** [comment]
Thanks for looking int this, but huh.  Even after deleting my .emacs.d and starting over, I'm still getting this error.  I've attached a backtrace in case that helps.

[debug.txt](https://github.com/rexim/org-cliplink/files/2975270/debug.txt)

**Comment by rexim** [comment]
@notuntoward do you have any problems connected to that website using curl?

```console
$ curl https://www.deepl.com/translator
```

**Comment by notuntoward** [comment]
curl works, printing html in the terminal

But... I'm no longer having this problem.  It might have something to do with moving from Germany to the US.  I don't know.

Since I can't reproduce the problem now, I'll close this bug.

**Comment by AtomicNess123** [comment]
I am actually having this problem. Whenever I use org-cliplink nothing gets copied when I have the link in the clipboard. I must actually call org-cliplink-capture first, then I run org-cliplink and it works for some reason. Any ideas?
