### ISSUE TITLE
Frequent error: error in process sentinel: let: Args out of range

### ISSUE THREAD

**Issue by jackbaty** [rexim/org-cliplink#123]
I often see an error when running org-cliplink...

For example, this url: https://daringfireball.net/linked/2019/10/10/apple-pulls-hkmaps

```
Contacting host: daringfireball.net:443
error in process sentinel: let: Args out of range: #<buffer  *http daringfireball.net:443*-610726>, 1, 2
error in process sentinel: Args out of range: #<buffer  *http daringfireball.net:443*-610726>, 1, 2
```

This doesn't happen for all URLs, and I can't seem to find a pattern.

Org mode version 9.2.6
Emacs version 26.2 (macOS Catalina but this also happened in Mojave)

Any idea where to start looking?

**Comment by azzamsa** [comment]
Yeah, sometimes this also happened to me, but it's very rare. 

I've tried the link above and worked at the first try. yes, sometime I face `args out of range` then I just repeat it, and it works.

I also didn't have any clue for this behavior.

**Comment by rexim** [comment]
Doesn't happen to me on `26.1`. Must be something that got broken in `26.2`. I'll take a look into it as soon as I get a chance.

**Comment by stefanfisk** [comment]
I'm trying out cliplink for the first time, and of course this happened on the first URL I was trying on 😸

This URL works great: https://emacs.stackexchange.com/questions/3280/orgmode-insert-link-from-clipboard
This one breaks with said error: https://itrevolution.com/love-letter-to-clojure-part-1/

Emacs 26.2 on Mojave, org 9.2.6.

**Comment by azzamsa** [comment]
It works for me at the first try (yes, I'm using 26.1). Maybe the problem only occurred in 26.2

**Comment by x-ji** [comment]
Happens to me if I try any Github link. 

```
Contacting host: github.com:443
error in process sentinel: org-cliplink-extract-and-prepare-title-from-current-buffer: Args out of range: #<buffer  *http github.com:443*>, 1, 2
error in process sentinel: Args out of range: #<buffer  *http github.com:443*>, 1, 2
error in process sentinel: org-cliplink-extract-and-prepare-title-from-current-buffer: Args out of range: #<buffer  *http github.com:443*-484244>, 1, 2
error in process sentinel: Args out of range: #<buffer  *http github.com:443*-484244>, 1, 2
```

Version info:

```
Org mode version 9.4 (9.4-elpaplus @ /Users/jx/.emacs.d/elpa/develop/org-plus-contrib-20200914/)
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-08-16
```

**Comment by mitdemrad** [comment]
I recently tried this on Mac OS Big Sur and was experiencing this problem. My work around was to change the variable **org-cliplink-transport-implementation** to **curl** and so far all the links I have tried started working. Seems like it is a problem with the default way of fetching the page which is url-el.
