### ISSUE TITLE
Require?

### ISSUE THREAD

**Issue by AtomicNess123** [rexim/org-cliplink#124]
I notice that I did not include (require 'org-cliplink) and the package is working. Is require needed at all?

**Comment by rexim** [comment]
@Gahamelas this is how [Autoload](https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html) works afaik.

`org-cliplink` function is marked with the [autoload cookie](https://github.com/rexim/org-cliplink/blob/82402cae7e118d67de7328417fd018a18f95fac2/org-cliplink.el#L577-L578) so the library should be automatically loaded when you first time call the function.

**Comment by rexim** [comment]
This is actually a pretty common practice among Emacs extensions.

**Comment by Gahamelas** [comment]
Thanks for illustrating me. How do I know in the future if a package is marked with the autoload cookie?

**Comment by rexim** [comment]
I have no idea! :) Maybe there is some sort of standard method, but I usually just try to use the package without require and if it doesn't work I add it. :D

**Comment by Gahamelas** [comment]
Thanks! As a beginner in Emacs, I know there is a way by using the function "autoload", but I haven't gotten around to learning it. But my init takes half a minute to load... with all the "requires" I got there... :P
