### ISSUE TITLE
Leaves .gz files in /tmp

### ISSUE THREAD

**Issue by alphapapa** [rexim/org-cliplink#73]
I've been enjoying using org-cliplink.  Thanks for making it!

I noticed that it is leaving `gz` files in `/tmp`.  Not a big deal, but it's a little messy.  :)

**Comment by rexim** [comment]
Hi @alphapapa,

Thanks for the report! I'm really glad that you enjoy org-cliplink. :) It creates `gz`s in `/tmp` because of a little trick for parsing gzipped responses. I'll try to make it remove `gz`s after they are not needed.

Thanks!

**Comment by Newlifer** [comment]
I second this

**Comment by rexim** [comment]
@alphapapa should be fixed now. Please check when you get a chance. :)

**Comment by alphapapa** [comment]
Thanks!
