### ISSUE TITLE
Utilize zlib support in gzip handling

### ISSUE THREAD

**Issue by rexim** [rexim/org-cliplink#89]
Derived from #85 
Related to #78 

When we receive gziped content:
- First, we check weather Emacs is compiled with zlib support. If it is then nothing is required here. Emacs will do pretty much all the work
- If zlib support is not available we use our hack with saving the gziped content to the file system and opening it with auto-compression-mode.
- If auto-compression-mode fails because of not found `gzip` program, we advise the user to use emacs with zlib support or install gzip.

**Comment by alphapapa** [comment]
Cool, thanks for working on this, it'll be a nice improvement.

**Comment by rexim** [comment]
@alphapapa hello and thank you for the feedback! May I ask you a question? Did you experience any problems with org-cliplink because of lack of the behavior described in this issue?

**Comment by alphapapa** [comment]
No problems, I just noticed some org-cliplink*.gz files laying around now and then.  Not a problem though, /tmp gets cleared out.  :)

**Comment by rexim** [comment]
@alphapapa Ah, you even filed an issue for that #73! But I thought I fixed that, didn't I?

That's actually interesting. Thanks for pointing that out! I just realized that the .gz files are cleaned out only when there were no errors during uncompressing the request! But if something goes wrong the .gz's are left in the temp directory. Let me file an issue for that...

**Comment by alphapapa** [comment]
Ah, that explains it!  Thanks.

**Comment by rexim** [comment]
@alphapapa please let me know if gunzipping of temp files is gone on the latest version. ;)
